version: '3.7'
services:
  worker:
    image: dr.meskatech.com/timing2paprika:latest
    restart: unless-stopped
    environment:
      - TIMING_TOKEN=******
      - TIMING_URL=******
      - TELEGRAM_CHAT_ID=******
      - PAPRIKA_URL=******
      - PAPRIKA_USERNAME=******
      - PAPRIKA_PASSWORD=******
      - PAPRIKA_PASSWORD2=******
      - PAPRIKA_DB=******
      - SENTRY_DSN=******
      - REDIS_URL=redis://redis:6379

  redis:
    image: redis:latest
    restart: unless-stopped
